### ISSUE TITLE
Deploy on Heroku crashing

### ISSUE THREAD

**Issue by kibray** [FormAPI/craco-less#10]
Hi @ndbroadbent, i'm just facing an issue deploying on Heroku that crash the application.
I'm using this configuaration: 
```
"@craco/craco": "^3.6.0",
"antd": "^3.15.1",
"craco-antd": "^1.10.0",
"react": "^16.8.4",
"react-dom": "^16.8.4",
"engines": {
    "node": "11.12.0"
  }
```
and I'm getting this error in heroku logs:
```
 > craco start
/app/node_modules/@craco/craco/lib/plugin-utils.js:29
throw new Error(
     ^
Error: Found an unhandled loader in the production webpack config: /app/node_modules/style-loader/index.js
```

I tried to update craco-less but didn't work :(

**Comment by ndbroadbent** [comment]
Hi @kibray, I don't think this is the correct way to deploy an application to Heroku. You're not meant to run `craco start` during production, it's only for development while you are testing the application locally. In production, you should be running `craco build` to build the static files, and then host these static files somewhere like Netlify, or in an S3 bucket. (Or you can also host static files on Heroku, and serve them from the backend server.)

Here's some documentation about deployment: https://facebook.github.io/create-react-app/docs/deployment

Please let me know if you are still running into any issues after that

**Comment by kibray** [comment]
@ndbroadbent thank you for your replay, it helped a lot. I solved my problem deploying on Netlify.
But just to let you know, I'm using Heroku (and now Netlify) as my development server, so I was actually using that server to host a build version (craco start was hiding a building script :) _yarn build_  and on Heroku is crashing. 
Thank you anyway!
