### ISSUE TITLE
react-scripts upgraded, craco-less got an error

### ISSUE THREAD

**Issue by nanxiaobei** [FormAPI/craco-less#5]
![error](https://wx1.sinaimg.cn/large/6645a88fgy1fyddw8yl48j21ei0jsgof.jpg)

**Comment by ndbroadbent** [comment]
Hi @nanxiaobei, thanks for letting me know about this error. But that's very strange, because [`react-scripts` hasn't released a new version](https://www.npmjs.com/package/react-scripts). 

Are you using version `2.1.1`?

Can you please post your `craco.config.js`?

**Comment by nanxiaobei** [comment]
Oh I understand, like I've changed the webpack config, then passed to `craco-less`, thanks for your replay, I'll check my code.

**Comment by ndbroadbent** [comment]
Yes that could be the problem. `craco-less` copies the settings from the SASS configuration, so it would be better to move the `craco-less` plugin to the top of the list, and then modify the webpack configuration after that.

Please let me know if you still run into any issues
