### ISSUE TITLE
Semantic UI support

### ISSUE THREAD

**Issue by olessavluk** [FormAPI/craco-less#8]
Hello 👋

I am trying to build [Semantic UI LESS](https://github.com/Semantic-Org/Semantic-UI-LESS) distribution, but get the following error:
```
./src/semantic/semantic.less (./node_modules/css-loader??ref--6-oneOf-8-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--6-oneOf-8-3!./src/semantic/semantic.less)

module.exports = __webpack_public_path__ + "static/media/theme.9cb07199.config";
             ^
Unrecognised input
      in /Users/olessavluk/work/semantic-ui-cra/src/semantic/theme.config (line 1, column 15)
```

However when I try to use "clean webpack", just with default less-loader configuration it works fine. Any idea why this might happen and how to fix it?

Repo to reproduce this issue - https://github.com/olessavluk/semantic-ui-cra

**Comment by olessavluk** [comment]
I was able to fix this by excluding this extensions from `file-loader`, see https://github.com/olessavluk/craco-less/commit/cfdd3080dee35ed3c54f61eecc33d39a2285cbc9

However it seems to be i bit hacky and I am not sure why webpack loaders used for `@import`, shouldn't it be done by LESS itself?

**Comment by olessavluk** [comment]
Hi @patricklafrance 

That's interesting, could you please share some problems that you have encountered when you have used SUI directly in the app? This would be very helpful for me.

For now, I have ended up with the setup like this - https://github.com/olessavluk/semantic-ui-cra. Idea is to have the ability to use LESS variables in site-specific styles and build everything using just 1 command.

Thanks!

**Comment by jbadeau** [comment]
And fix planned?

**Comment by theres** [comment]
I've managed to make it works for me. `craco.config.js`:

```js
const CracoLessPlugin= require("craco-less");
const { getLoader, loaderByName } = require("@craco/craco");
const path = require('path');

module.exports = {
  webpack: {
    configure (webpackConfig) {
      webpackConfig.resolve.alias = {
        '../../theme.config': path.join(__dirname, './src/theme.config'),
        '../../node_modules/semantic-ui-less/themes/default/elements/assets': path.resolve(__dirname, './node_modules/semantic-ui-less/themes/default/assets/')
      }

      const { isFound, match } = getLoader(webpackConfig, loaderByName("file-loader"));
      if (isFound) {
        match.loader.exclude = [...match.loader.exclude,  /\.(config|overrides|variables)$/]
      }

      return webpackConfig;
    }
  },
  plugins: [
    {
      plugin: CracoLessPlugin,
      options: {
        cssLoaderOptions: {
          modules: 'global',
          localIdentName: "[local]_[hash:base64:5]"
        }
      }
    }
  ]
};
```

**Comment by olessavluk** [comment]
Fix for this issue can be implemented by using fork with custom `exclude` or as @theres suggested
